Normalization did not come a better result

In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold, cross_val_score, GridSearchCV

In [2]:
train_path = '../../preprocess_train_dataset/pre08_train.csv'
test_path = '../../preprocess_test_dataset/pre08_test.csv'
pid_path = '../../spaceship-titanic_rawData/sample_submission.csv'

train = pd.read_csv(train_path)
test = pd.read_csv(test_path)
pid = pd.read_csv(pid_path)

train_x = train.drop('Transported', axis=1)
train_y = train['Transported']
sub_pid = pid['PassengerId']

train_x

,CryoSleep,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,Cabin_deck_A,Cabin_deck_B,Cabin_deck_C,Cabin_deck_D,Cabin_deck_E,Cabin_deck_F,...,Age_Categ_High,Age_Categ_VeryHigh,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,spending_Categ_Low,spending_Categ_Medium,spending_Categ_High
0,False,False,True,False,False,True,False,False,False,False,...,True,False,0.0,0.0,0.0,0.0,0.0,True,False,False
1,False,True,False,False,False,False,False,False,False,True,...,False,False,109.0,9.0,25.0,549.0,44.0,False,True,False
2,False,False,True,False,True,False,False,False,False,False,...,False,True,43.0,3576.0,0.0,6715.0,49.0,False,False,True
3,False,False,True,False,True,False,False,False,False,False,...,False,False,0.0,1283.0,371.0,3329.0,193.0,False,False,True
4,False,True,False,False,False,False,False,False,False,True,...,False,False,303.0,70.0,151.0,565.0,2.0,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,False,False,True,False,True,False,False,False,False,False,...,True,False,0.0,6819.0,0.0,1643.0,74.0,False,False,True
8689,True,True,False,False,False,False,False,False,False,False,...,False,False,0.0,0.0,0.0,0.0,0.0,True,False,False
8690,False,True,False,False,False,False,False,False,False,False,...,False,False,0.0,0.0,1872.0,1.0,0.0,False,True,False
8691,False,False,True,False,False,False,False,False,True,False,...,False,False,0.0,1049.0,0.0,353.0,3235.0,False,False,True
8692,False,False,True,False,False,False,False,False,True,False,...,True,False,126.0,4688.0,0.0,0.0,12.0,False,False,True

In [3]:
kFold = KFold(n_splits=10)
rf = RandomForestClassifier()

score = cross_val_score(rf, train_x, train_y, cv = kFold)

print('Cross Validation Score: ', score)
print('Mean Score: ', score.mean())

Cross Validation Score:  [0.8045977  0.76781609 0.77471264 0.79631761 0.78941312 0.81012658
 0.81127733 0.82048331 0.79401611 0.77790564]
Mean Score:  0.7946666137587133

In [4]:
# submission
rf = RandomForestClassifier(n_estimators=200, max_depth=12, min_samples_split=15, min_samples_leaf=5, bootstrap=True, criterion='entropy')


rf.fit(train_x, train_y)
pred = rf.predict(test)

rf_submission = pd.DataFrame({'PassengerId': sub_pid, 'Transported': pred})

rf_submission.isna().sum()

PassengerId    0
Transported    0
dtype: int64

In [5]:
rf_submission.to_csv('../../output_prediction/rf06v1_submission.csv', index=False, index_label='PassengerId')